---
services:
  orazen:
    image: orazenorg/orazen:stable
    # image: orazenorg/orazen:develop
    # Use plotting image
    # image: orazenorg/orazen:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: orazen
    volumes:
      - "./user_data:/orazen/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.orazen.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /orazen/user_data/logs/orazen.log
      --db-url sqlite:////orazen/user_data/tradesv3.sqlite
      --config /orazen/user_data/config.json
      --strategy SampleStrategy
